spring.datasource.url=${DB_URL:jdbc:postgresql://ep-wild-star-b5v51m0m-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_XHkjeqW2zyc1}
